# CAD AutoLisp 图元名组码

## 获取图元属性

```lisp
(entget(car(entsel)))			;; 列出所选图元的所有属性信息
(entget(car(entsel)) '("*"))	;; 列出所选图元的所有属性信息（包括扩展数据）
```

## 获取选择的图元信息

```lisp
(defun c:T1()
  (setq a (entsel));获取图元名
  (setq a (car a))
  (entget a)
)
```

## 循环选择图元，并显示所选图元的图层名

```lisp
(setq a (entget (car (entsel))));获取图元的组码

(cdr (assoc 0 a))

(entget (car (entsel)))

(while (= 1 1)
	(while (= (setq a (car (entsel))) nil))
	(setq ent (cdr (assoc 8 (entget a))))
	(print ent)
)
```

## 组码

```lisp
;1、如果62存在
(setq ent (entget (car (entsel))));获取组码
(setq ent (subst (cons 62 3) (assoc 62 ent) ent));替换62组码
(entmod ent)

;1、如果62存在
;替换组码内的信息
;更新组码信息

;2、如果62不存在
;组合新的表

(setq ent (entget (car (entsel))));获取组码
(setq a (list (cons 62 2)));颜色信息

(entmod (append ent a))
```