# CAD AutoLisp 多边形建议用法

## 外切多边形

```lisp
(defun C:w3()  (setvar "cmdecho" 0) (command "POLYGON" 3 pause "C" pause) (princ))
(defun C:w4()  (setvar "cmdecho" 0) (command "POLYGON" 4 pause "C" pause) (princ))
(defun C:w5()  (setvar "cmdecho" 0) (command "POLYGON" 5 pause "C" pause) (princ))
(defun C:w6()  (setvar "cmdecho" 0) (command "POLYGON" 6 pause "C" pause) (princ))
(defun C:w7()  (setvar "cmdecho" 0) (command "POLYGON" 7 pause "C" pause) (princ))
(defun C:w8()  (setvar "cmdecho" 0) (command "POLYGON" 8 pause "C" pause) (princ))
(defun C:w9()  (setvar "cmdecho" 0) (command "POLYGON" 9 pause "C" pause) (princ))
```

## 内接多边形

```lisp
(defun C:n3()  (setvar "cmdecho" 0) (command "POLYGON" 3 pause "i" pause) (princ))
(defun C:n4()  (setvar "cmdecho" 0) (command "POLYGON" 4 pause "i" pause) (princ))
(defun C:n5()  (setvar "cmdecho" 0) (command "POLYGON" 5 pause "i" pause) (princ))
(defun C:n6()  (setvar "cmdecho" 0) (command "POLYGON" 6 pause "i" pause) (princ))
(defun C:n7()  (setvar "cmdecho" 0) (command "POLYGON" 7 pause "i" pause) (princ))
(defun C:n8()  (setvar "cmdecho" 0) (command "POLYGON" 8 pause "i" pause) (princ))
(defun C:n9()  (setvar "cmdecho" 0) (command "POLYGON" 9 pause "i" pause) (princ))
```

## 边模式多边形

```lisp
(defun C:b3()  (setvar "cmdecho" 0) (command "POLYGON" 3 "E" pause pause) (princ))
(defun C:b4()  (setvar "cmdecho" 0) (command "POLYGON" 4 "E" pause pause) (princ))
(defun C:b5()  (setvar "cmdecho" 0) (command "POLYGON" 5 "E" pause pause) (princ))
(defun C:b6()  (setvar "cmdecho" 0) (command "POLYGON" 6 "E" pause pause) (princ))
(defun C:b7()  (setvar "cmdecho" 0) (command "POLYGON" 7 "E" pause pause) (princ))
(defun C:b8()  (setvar "cmdecho" 0) (command "POLYGON" 8 "E" pause pause) (princ))
(defun C:b9()  (setvar "cmdecho" 0) (command "POLYGON" 9 "E" pause pause) (princ))
```